pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Savitha11111/my-flask-app.git'
            }
        }

        stage('Build') {
            steps {
                sh 'docker build -t flask-app .'
            }
        }

        stage('Test') {
            steps {
                sh 'docker run --rm flask-app python -m unittest discover -s tests'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run -d -p 5000:5000 flask-app'
            }
        }
    }
}
