pipeline {
    agent any

    environment {
        VIRTUAL_ENV = "${WORKSPACE}/venv"
    }

    stages {
        stage('Setup') {
            steps {
                bat 'python -m pip install --upgrade pip'
                bat 'python -m venv ${VIRTUAL_ENV}'
                bat 'call ${VIRTUAL_ENV}/Scripts/activate'
            }
        }
        stage('Install Dependencies') {
            steps {
                bat 'call ${VIRTUAL_ENV}/Scripts/activate && pip install -r requirements.txt'
            }
        }
        stage('Run Flask App') {
            steps {
                bat 'call ${VIRTUAL_ENV}/Scripts/activate && python app.py'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
        }
        success {
            echo 'Build and test successful!'
        }
        failure {
            echo 'Build or test failed!'
        }
    }
}
