       pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
               git 'https://github.com/Savitha11111/my-flask-app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Test') {
            steps {
                sh 'python -m unittest tests.py'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploy stage is currently empty. Add deployment commands here.'
            }
        }
    }
}
